[[entry]]
played_at = "2026-06-25T05:55:16Z"
path = "https://www.youtube.com/watch?v=vqswOmIn6PY"
title = "Ratt - Out of the Cellar (Full Album 1984)"
artist = "Mr.Gaetano"
duration_secs = 2239

[[entry]]
played_at = "2026-06-22T05:53:12Z"
path = "https://www.youtube.com/watch?v=HWtlDuzHc4g"
title = "Slowdive - skin in the game (Official Visualizer)"
artist = "Slowdive Official"
duration_secs = 233

[[entry]]
played_at = "2026-06-22T05:49:19Z"
path = "https://www.youtube.com/watch?v=G9RpHfPyEx8"
title = "Slowdive - kisses (Official Video)"
artist = "Slowdive Official"
duration_secs = 238

[[entry]]
played_at = "2026-06-22T05:45:15Z"
path = "https://www.youtube.com/watch?v=XvMLeQCU8ew"
title = "prayer remembered"
artist = "Slowdive Official"
duration_secs = 287

[[entry]]
played_at = "2026-06-22T05:42:11Z"
path = "https://www.youtube.com/watch?v=vQiJrhcwfk0"
title = "shanty"
artist = "Slowdive Official"
duration_secs = 348

[[entry]]
played_at = "2026-06-22T01:35:50Z"
path = "https://www.youtube.com/watch?v=WyihFDfE9Q4"
title = "Lazer Blazer"
artist = "hyperdrive sound"
duration_secs = 3603

[[entry]]
played_at = "2026-06-04T04:55:28Z"
path = "https://www.youtube.com/watch?v=Kd8FFlH3wrg"
title = "The Current State of Deadlock | The Bear Pit"
artist = "The Bear Pit"
duration_secs = 4338

[[entry]]
played_at = "2026-06-04T03:31:22Z"
path = "https://www.youtube.com/watch?v=0u8teXR8VE4"
title = "RATT - Round And Round (Official Music Video)"
artist = "RHINO"
duration_secs = 266

[[entry]]
played_at = "2026-06-03T06:25:37Z"
path = "https://www.youtube.com/watch?v=AkFqg5wAuFk"
title = "Pantera - Walk (Official Music Video) [4K]"
artist = "Pantera"
duration_secs = 316

[[entry]]
played_at = "2026-06-03T06:20:21Z"
path = "https://www.youtube.com/watch?v=EqQuihD0hoI"
title = "Rob Zombie - Dragula"
artist = "Rob Zombie"
duration_secs = 228

[[entry]]
played_at = "2026-06-03T06:16:33Z"
path = "https://www.youtube.com/watch?v=CD-E-LDc384"
title = "Metallica: Enter Sandman (Official Music Video)"
artist = "Metallica"
duration_secs = 331

[[entry]]
played_at = "2026-06-03T06:11:02Z"
path = "https://www.youtube.com/watch?v=SRwrg0db_zY"
title = "Twisted Sister - I Wanna Rock (Official Music Video)"
artist = "Twisted Sister"
duration_secs = 274

[[entry]]
played_at = "2026-06-03T06:06:29Z"
path = "https://www.youtube.com/watch?v=Ghd2bkIadG4"
title = "Skid Row - 18 And Life (Official Music Video)"
artist = "RHINO"
duration_secs = 234

[[entry]]
played_at = "2026-06-03T06:02:35Z"
path = "https://www.youtube.com/watch?v=6yP1tcy9a10"
title = "Scorpions - Rock You Like A Hurricane (Official Music Video)"
artist = "Scorpions"
duration_secs = 253

[[entry]]
played_at = "2026-06-03T05:57:17Z"
path = "https://www.youtube.com/watch?v=fuKDBPw8wQA"
title = "Van Halen - Panama (Official Music Video)"
artist = "Van Halen"
duration_secs = 223

[[entry]]
played_at = "2026-06-03T05:53:35Z"
path = "https://www.youtube.com/watch?v=Qq4j1LtCdww"
title = "Alice Cooper - Poison"
artist = "Official Alice Cooper"
duration_secs = 269

[[entry]]
played_at = "2026-06-03T05:47:44Z"
path = "https://www.youtube.com/watch?v=gStvjANqoqs"
title = "Quiet Riot - Mama Weer All Crazee Now"
artist = "QuietRiotVEVO"
duration_secs = 261

[[entry]]
played_at = "2026-06-03T05:43:24Z"
path = "https://www.youtube.com/watch?v=v2AC41dglnM"
title = "AC/DC - Thunderstruck (Official Video)"
artist = "AC/DC"
duration_secs = 293

[[entry]]
played_at = "2026-06-03T05:29:39Z"
path = "https://www.youtube.com/watch?v=brKzBs6zDXc"
title = "RHINO BUCKET - WELCOME TO HELL"
artist = "rhinobuckethead"
duration_secs = 253

[[entry]]
played_at = "2026-06-03T05:25:06Z"
path = "https://www.youtube.com/watch?v=i28UEoLXVFQ"
title = "Cinderella - Don't Know What You Got (Till It's Gone)"
artist = "Cinderella"
duration_secs = 349

[[entry]]
played_at = "2026-06-03T05:16:46Z"
path = "https://www.youtube.com/watch?v=BKoxeZpNk_M"
title = "Firehouse - Don't Walk Away"
artist = "firehouse0910"
duration_secs = 273

[[entry]]
played_at = "2026-06-03T05:11:26Z"
path = "https://www.youtube.com/watch?v=kMEz4cFMlZE"
title = "Quiet Riot - Metal Health (Bang Your Head) - HQ Audio"
artist = "Hard Rock & Heavy Metal"
duration_secs = 322

[[entry]]
played_at = "2026-06-02T05:26:58Z"
path = "https://www.youtube.com/watch?v=8_W3OLa9aG8"
title = "Tonymelodics - Kryptops LP [STRAFTAT Soundtrack] (2023)"
artist = "solarsoundzFM"
duration_secs = 1425

[[entry]]
played_at = "2026-06-02T04:51:58Z"
path = "https://www.youtube.com/watch?v=8_W3OLa9aG8"
title = "Tonymelodics - Kryptops LP [STRAFTAT Soundtrack] (2023)"
artist = "solarsoundzFM"
duration_secs = 1425

[[entry]]
played_at = "2026-06-01T23:02:08Z"
path = "https://www.youtube.com/watch?v=pzgf66pS7Wc"
title = "Deku Palace Garden"
artist = "ROZEN"
duration_secs = 168

[[entry]]
played_at = "2026-06-01T23:01:27Z"
path = "https://www.youtube.com/watch?v=Q42CF4_ixb4"
title = "Ordon Village (Night)"
artist = "ROZEN"
duration_secs = 154

[[entry]]
played_at = "2026-06-01T23:00:50Z"
path = "https://www.youtube.com/watch?v=DgD1kiK4CJo"
title = "Castle Town"
artist = "ROZEN"
duration_secs = 173

[[entry]]
played_at = "2026-06-01T06:09:34Z"
path = "https://www.youtube.com/watch?v=jP60q8Nos1Y"
title = "Riding (Epona)"
artist = "David Peacock"
duration_secs = 200

[[entry]]
played_at = "2026-06-01T06:06:14Z"
path = "https://www.youtube.com/watch?v=iLHpUMzDKxU"
title = "Lost Woods"
artist = "ROZEN"
duration_secs = 297

[[entry]]
played_at = "2026-06-01T06:01:18Z"
path = "https://www.youtube.com/watch?v=3WxTQkJ-02g"
title = "Kokiri Forest"
artist = "ROZEN"
duration_secs = 100

[[entry]]
played_at = "2026-06-01T05:59:38Z"
path = "https://www.youtube.com/watch?v=Am6TA9u2Kec"
title = "Dark World Fragments"
artist = "David Peacock"
duration_secs = 300

[[entry]]
played_at = "2026-06-01T05:54:39Z"
path = "https://www.youtube.com/watch?v=3LXGG5xQc2Y"
title = "Legendary Hero"
artist = "ROZEN"
duration_secs = 189

[[entry]]
played_at = "2026-06-01T05:50:20Z"
path = "https://music.youtube.com/watch?v=ElkEApnV0yI"
title = "Ocarina of Time"
artist = "ROZEN"
duration_secs = 202

[[entry]]
played_at = "2026-06-01T05:42:35Z"
path = "https://music.youtube.com/watch?v=ElkEApnV0yI"
title = "Ocarina of Time"
artist = "ROZEN"
duration_secs = 202

[[entry]]
played_at = "2026-06-01T05:34:51Z"
path = "https://www.youtube.com/watch?v=VI91fJJF2YQ"
title = "[OJV] The Legend of Zelda: Ocarina of Time - Live Orchestra"
artist = "L'Orchestre de Jeux Vidéo - OJV"
duration_secs = 852

[[entry]]
played_at = "2026-06-01T00:44:57Z"
path = "https://www.youtube.com/watch?v=bUMS8Ut9ybA"
title = "Zelda: Ocarina of Time Piano Medley (Extended) Nostalgia Edition"
artist = "Erik C 'Piano Man'"
duration_secs = 590

[[entry]]
played_at = "2026-05-21T05:52:40Z"
path = "https://www.youtube.com/watch?v=se647BHCyQ0"
title = "◄ Neurofunk Mix ► Dirty & Dark DnB ☠"
artist = "Db One - DnB Channel"
duration_secs = 3636

[[entry]]
played_at = "2026-05-19T04:30:26Z"
path = "https://www.youtube.com/watch?v=se647BHCyQ0"
title = "◄ Neurofunk Mix ► Dirty & Dark DnB ☠"
artist = "Db One - DnB Channel"
duration_secs = 3636

[[entry]]
played_at = "2026-05-19T03:29:51Z"
path = "https://www.youtube.com/watch?v=se647BHCyQ0"
title = "◄ Neurofunk Mix ► Dirty & Dark DnB ☠"
artist = "Db One - DnB Channel"
duration_secs = 3636

[[entry]]
played_at = "2026-05-19T01:41:49Z"
path = "https://www.youtube.com/watch?v=18-vtgJHHmM"
title = "Deep Neurofunk DnB Mix (DBM肆)"
artist = "ヤマラ（Music）"
duration_secs = 4640

[[entry]]
played_at = "2026-05-18T04:39:54Z"
path = "https://www.youtube.com/watch?v=y6Ya0zIGYxI"
title = "Corrupt Souls - Live in Sevilla - 20/05/2005 #dnb #electronic #neurofunk"
artist = "Katzilla DNB"
duration_secs = 6121

[[entry]]
played_at = "2026-05-18T00:47:27Z"
path = "https://music.youtube.com/watch?v=m-BEAKGllM0"
title = "Be Thankful For What You've Got (Live)"
artist = "ORGŌNE"
duration_secs = 535

[[entry]]
played_at = "2026-05-18T00:38:33Z"
path = "https://music.youtube.com/watch?v=ZDM-AB-ErpQ"
title = "Heaven's Only Wishful (Extended Version)"
artist = "MorMor Music"
duration_secs = 322

[[entry]]
played_at = "2026-05-18T00:33:11Z"
path = "https://music.youtube.com/watch?v=9GrVM_Mp-O4"
title = "Perfect Dark: Main Titles HD"
artist = "Video-Game OST HQ"
duration_secs = 31

[[entry]]
played_at = "2026-05-18T00:32:40Z"
path = "https://music.youtube.com/watch?v=p9RqEzv2QoQ"
title = "Perfect Dark: Main Titles: Hurry! HD"
artist = "Video-Game OST HQ"
duration_secs = 17

[[entry]]
played_at = "2026-05-18T00:32:24Z"
path = "https://music.youtube.com/watch?v=KRqUJsbcmoc"
title = "Perfect Dark: Perfect Menu Intro HD"
artist = "Video-Game OST HQ"
duration_secs = 16

[[entry]]
played_at = "2026-05-18T00:32:09Z"
path = "https://music.youtube.com/watch?v=kJqG6upTrIc"
title = "Perfect Dark: Institute Menu HD"
artist = "Video-Game OST HQ"
duration_secs = 149

[[entry]]
played_at = "2026-05-18T00:29:40Z"
path = "https://music.youtube.com/watch?v=9GrVM_Mp-O4"
title = "Perfect Dark: Main Titles HD"
artist = "Video-Game OST HQ"
duration_secs = 31

[[entry]]
played_at = "2026-05-18T00:29:10Z"
path = "https://music.youtube.com/watch?v=p9RqEzv2QoQ"
title = "Perfect Dark: Main Titles: Hurry! HD"
artist = "Video-Game OST HQ"
duration_secs = 17

[[entry]]
played_at = "2026-05-18T00:28:54Z"
path = "https://music.youtube.com/watch?v=KRqUJsbcmoc"
title = "Perfect Dark: Perfect Menu Intro HD"
artist = "Video-Game OST HQ"
duration_secs = 16

[[entry]]
played_at = "2026-05-18T00:28:39Z"
path = "https://music.youtube.com/watch?v=zt4HV1YQZZ0"
title = "Perfect Dark: Carrington Institute HD"
artist = "Video-Game OST HQ"
duration_secs = 320

[[entry]]
played_at = "2026-05-18T00:23:20Z"
path = "https://music.youtube.com/watch?v=tllU3Vrsi_8"
title = "Perfect Dark: Enter the Dark HD"
artist = "Video-Game OST HQ"
duration_secs = 72

[[entry]]
played_at = "2026-05-18T00:22:08Z"
path = "https://music.youtube.com/watch?v=EtgApoQPswE"
title = "Perfect Dark: dataDyne Central: Defection HD"
artist = "Video-Game OST HQ"
duration_secs = 485

[[entry]]
played_at = "2026-05-18T00:14:03Z"
path = "https://music.youtube.com/watch?v=u-83gJUMvZs"
title = "Perfect Dark: dataDyne Central: Defection (CD Version) HD"
artist = "Video-Game OST HQ"
duration_secs = 485

[[entry]]
played_at = "2026-05-18T00:05:59Z"
path = "https://music.youtube.com/watch?v=oJBXS6Xlvlo"
title = "Perfect Dark: dataDyne Central: Defection X HD"
artist = "Video-Game OST HQ"
duration_secs = 179

[[entry]]
played_at = "2026-05-18T00:03:00Z"
path = "https://music.youtube.com/watch?v=NATsGXOReiY"
title = "Perfect Dark: dataDyne Central: Defection Outro: Quick Descent HD"
artist = "Video-Game OST HQ"
duration_secs = 15

[[entry]]
played_at = "2026-05-18T00:02:45Z"
path = "https://music.youtube.com/watch?v=xA4wjI2d6wY"
title = "Perfect Dark: dataDyne Research: Investigation Intro: Going Down HD"
artist = "Video-Game OST HQ"
duration_secs = 37

[[entry]]
played_at = "2026-05-18T00:02:09Z"
path = "https://music.youtube.com/watch?v=SC5K5ETI_YI"
title = "Perfect Dark: dataDyne Research: Investigation HD"
artist = "Video-Game OST HQ"
duration_secs = 417

[[entry]]
played_at = "2026-05-17T23:55:12Z"
path = "https://music.youtube.com/watch?v=wY_cClj8j0k"
title = "Perfect Dark: dataDyne Research: Investigation X HD"
artist = "Video-Game OST HQ"
duration_secs = 152

[[entry]]
played_at = "2026-05-17T23:52:41Z"
path = "https://music.youtube.com/watch?v=hrTOoJUl6Z4"
title = "Perfect Dark: dataDyne Research: Investigation Outro: Meet the Doctor HD"
artist = "Video-Game OST HQ"
duration_secs = 52

[[entry]]
played_at = "2026-05-17T23:51:49Z"
path = "https://music.youtube.com/watch?v=g7FvnFSZXkw"
title = "Perfect Dark: dataDyne Central: Extraction Intro: Lights Out HD"
artist = "Video-Game OST HQ"
duration_secs = 28

[[entry]]
played_at = "2026-05-17T23:51:22Z"
path = "https://music.youtube.com/watch?v=W25jWcUPD-M"
title = "Perfect Dark: dataDyne Central: Extraction HD"
artist = "Video-Game OST HQ"
duration_secs = 292

[[entry]]
played_at = "2026-05-17T23:46:30Z"
path = "https://music.youtube.com/watch?v=IAjTmQmVyq0"
title = "Perfect Dark: dataDyne Central: Extraction X HD"
artist = "Video-Game OST HQ"
duration_secs = 139

[[entry]]
played_at = "2026-05-15T05:25:14Z"
path = "https://music.youtube.com/watch?v=W25jWcUPD-M"
title = "Perfect Dark: dataDyne Central: Extraction HD"
artist = "Video-Game OST HQ"
duration_secs = 292

[[entry]]
played_at = "2026-05-15T05:20:22Z"
path = "https://music.youtube.com/watch?v=g7FvnFSZXkw"
title = "Perfect Dark: dataDyne Central: Extraction Intro: Lights Out HD"
artist = "Video-Game OST HQ"
duration_secs = 28

[[entry]]
played_at = "2026-05-15T05:19:55Z"
path = "https://music.youtube.com/watch?v=hrTOoJUl6Z4"
title = "Perfect Dark: dataDyne Research: Investigation Outro: Meet the Doctor HD"
artist = "Video-Game OST HQ"
duration_secs = 52

[[entry]]
played_at = "2026-05-15T05:19:03Z"
path = "https://music.youtube.com/watch?v=wY_cClj8j0k"
title = "Perfect Dark: dataDyne Research: Investigation X HD"
artist = "Video-Game OST HQ"
duration_secs = 152

[[entry]]
played_at = "2026-05-15T05:16:32Z"
path = "https://music.youtube.com/watch?v=SC5K5ETI_YI"
title = "Perfect Dark: dataDyne Research: Investigation HD"
artist = "Video-Game OST HQ"
duration_secs = 417

[[entry]]
played_at = "2026-05-15T05:09:35Z"
path = "https://music.youtube.com/watch?v=xA4wjI2d6wY"
title = "Perfect Dark: dataDyne Research: Investigation Intro: Going Down HD"
artist = "Video-Game OST HQ"
duration_secs = 37

[[entry]]
played_at = "2026-05-15T05:08:59Z"
path = "https://music.youtube.com/watch?v=NATsGXOReiY"
title = "Perfect Dark: dataDyne Central: Defection Outro: Quick Descent HD"
artist = "Video-Game OST HQ"
duration_secs = 15

[[entry]]
played_at = "2026-05-15T05:08:44Z"
path = "https://music.youtube.com/watch?v=oJBXS6Xlvlo"
title = "Perfect Dark: dataDyne Central: Defection X HD"
artist = "Video-Game OST HQ"
duration_secs = 179

[[entry]]
played_at = "2026-05-15T05:05:45Z"
path = "https://music.youtube.com/watch?v=u-83gJUMvZs"
title = "Perfect Dark: dataDyne Central: Defection (CD Version) HD"
artist = "Video-Game OST HQ"
duration_secs = 485

[[entry]]
played_at = "2026-05-15T04:57:40Z"
path = "https://music.youtube.com/watch?v=EtgApoQPswE"
title = "Perfect Dark: dataDyne Central: Defection HD"
artist = "Video-Game OST HQ"
duration_secs = 485

[[entry]]
played_at = "2026-05-15T04:49:36Z"
path = "https://music.youtube.com/watch?v=tllU3Vrsi_8"
title = "Perfect Dark: Enter the Dark HD"
artist = "Video-Game OST HQ"
duration_secs = 72

[[entry]]
played_at = "2026-05-15T04:48:24Z"
path = "https://music.youtube.com/watch?v=zt4HV1YQZZ0"
title = "Perfect Dark: Carrington Institute HD"
artist = "Video-Game OST HQ"
duration_secs = 320

[[entry]]
played_at = "2026-05-15T04:13:21Z"
path = "https://music.youtube.com/watch?v=KRqUJsbcmoc"
title = "Perfect Dark: Perfect Menu Intro HD"
artist = "Video-Game OST HQ"
duration_secs = 16

[[entry]]
played_at = "2026-05-15T04:13:06Z"
path = "https://music.youtube.com/watch?v=p9RqEzv2QoQ"
title = "Perfect Dark: Main Titles: Hurry! HD"
artist = "Video-Game OST HQ"
duration_secs = 17

[[entry]]
played_at = "2026-05-15T04:12:50Z"
path = "https://music.youtube.com/watch?v=9GrVM_Mp-O4"
title = "Perfect Dark: Main Titles HD"
artist = "Video-Game OST HQ"
duration_secs = 31

[[entry]]
played_at = "2026-05-15T04:10:21Z"
path = "https://music.youtube.com/watch?v=kJqG6upTrIc"
title = "Perfect Dark: Institute Menu HD"
artist = "Video-Game OST HQ"
duration_secs = 149

[[entry]]
played_at = "2026-05-15T04:07:52Z"
path = "https://music.youtube.com/watch?v=KRqUJsbcmoc"
title = "Perfect Dark: Perfect Menu Intro HD"
artist = "Video-Game OST HQ"
duration_secs = 16

[[entry]]
played_at = "2026-05-15T04:07:37Z"
path = "https://music.youtube.com/watch?v=p9RqEzv2QoQ"
title = "Perfect Dark: Main Titles: Hurry! HD"
artist = "Video-Game OST HQ"
duration_secs = 17

[[entry]]
played_at = "2026-05-15T04:07:21Z"
path = "https://music.youtube.com/watch?v=9GrVM_Mp-O4"
title = "Perfect Dark: Main Titles HD"
artist = "Video-Game OST HQ"
duration_secs = 31

[[entry]]
played_at = "2026-05-15T02:01:17Z"
path = "https://music.youtube.com/watch?v=ZDM-AB-ErpQ"
title = "Heaven's Only Wishful (Extended Version)"
artist = "MorMor Music"
duration_secs = 322

[[entry]]
played_at = "2026-05-15T01:55:55Z"
path = "https://music.youtube.com/watch?v=m-BEAKGllM0"
title = "Be Thankful For What You've Got (Live)"
artist = "ORGŌNE"
duration_secs = 535

[[entry]]
played_at = "2026-05-15T01:47:01Z"
path = "https://music.youtube.com/watch?v=Gte3m_-jyCw"
title = "I Won't Be There"
artist = "Skinshape"
duration_secs = 423

[[entry]]
played_at = "2026-05-15T01:31:29Z"
path = "https://music.youtube.com/watch?v=39eq9PphAAk"
title = "Une Cellier"
artist = "Dale Cooper Quartet - Topic"
duration_secs = 669

[[entry]]
played_at = "2026-05-15T01:20:04Z"
path = "https://music.youtube.com/watch?v=X2cEtEebGPo"
title = "Prowler"
artist = "BOHREN & DER CLUB OF GORE"
duration_secs = 305

[[entry]]
played_at = "2026-05-15T01:15:00Z"
path = "https://music.youtube.com/watch?v=qHoeTjbFB28"
title = "Nighthawks"
artist = "Lowering - Topic"
duration_secs = 305

[[entry]]
played_at = "2026-05-15T01:09:56Z"
path = "https://music.youtube.com/watch?v=Zz1LMiut5Mc"
title = "Im Rauch"
artist = "BOHREN & DER CLUB OF GORE"
duration_secs = 330

[[entry]]
played_at = "2026-05-15T01:04:27Z"
path = "https://music.youtube.com/watch?v=Yzg6hT3n89o"
title = "Norwegian Horror Saga"
artist = "Manet - Topic"
duration_secs = 320

[[entry]]
played_at = "2026-05-15T00:06:59Z"
path = "https://www.youtube.com/watch?v=mOq07ZkrN-A"
title = "Oaysis: Outcry | SHADOW201-5-Y | Moving Shadow"
artist = "Moving Shadow HQ"
duration_secs = 376

[[entry]]
played_at = "2026-05-14T23:37:26Z"
path = "https://www.youtube.com/watch?v=t7QSzvK4iek"
title = "Moving Shadow Presents: 05.2 Mixed By Calyx"
artist = "D'n'B CD Archive"
duration_secs = 4340
