[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18485/1782017871/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Exposition"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 1
duration_secs = 64

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18486/1782017874/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Derecho"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 2
duration_secs = 170

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18487/1782017879/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Redwood"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 3
duration_secs = 175

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18488/1782017883/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "The Ballad of Dylan Owen"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 4
duration_secs = 146

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18489/1782017886/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Right Here and Now"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 5
duration_secs = 222

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18490/1782017890/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Gunfire in the Sky"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 6
duration_secs = 171

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18491/1782017894/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Rats"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 7
duration_secs = 190

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18492/1782017898/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Skeleton"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 8
duration_secs = 180

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18493/1782017902/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Cuckoo"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 9
duration_secs = 221

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18494/1782017908/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Forlorn Hope"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 10
duration_secs = 263

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18495/1782017913/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Prelude"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 11
duration_secs = 205

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18496/1782017917/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Thistle"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 12
duration_secs = 260

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18497/1782017922/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Hanging"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 13
duration_secs = 209

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18498/1782017927/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Lesser Known Good"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 14
duration_secs = 301

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18499/1782017931/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Seven Hills"
artist = "Nym"
album = "Warm Blooded Lizard"
track_number = 15
duration_secs = 215

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18510/1782017429/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Lionheart"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 1
duration_secs = 292

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18511/1782017434/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Wolf Drawn"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 2
duration_secs = 200

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18512/1782017439/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "When I Go"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 3
duration_secs = 339

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18513/1782017443/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "With Rainy Eyes"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 4
duration_secs = 300

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18514/1782017448/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "The Darkest Evening of the Year"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 5
duration_secs = 143

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18515/1782017459/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Eve"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 6
duration_secs = 350

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18516/1782017465/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Smoke Signals"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 7
duration_secs = 228

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18517/1782017469/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Periscope Up"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 8
duration_secs = 185

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18518/1782017475/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "First Snow"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 9
duration_secs = 312

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18519/1782017480/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Good Knight"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 10
duration_secs = 306

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18520/1782017483/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Soon It Will Be Cold Enough to Build Fires"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 11
duration_secs = 180

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18521/1782017496/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Anthem"
artist = "Emancipator"
album = "Soon It Will Be Cold Enough"
track_number = 12
duration_secs = 340

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18500/1782017656/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Intro"
artist = "Tor"
album = "Blue Book"
track_number = 1
duration_secs = 65

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18501/1782017659/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Two Suns"
artist = "Tor"
album = "Blue Book"
track_number = 2
duration_secs = 273

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18502/1782017665/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Loop Theory"
artist = "Tor"
album = "Blue Book"
track_number = 3
duration_secs = 213

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18503/1782017677/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Days Gone"
artist = "Tor"
album = "Blue Book"
track_number = 4
duration_secs = 266

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18504/1782017681/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Myth"
artist = "Tor"
album = "Blue Book"
track_number = 5
duration_secs = 259

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18505/1782017684/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Aeris"
artist = "Tor"
album = "Blue Book"
track_number = 6
duration_secs = 336

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18506/1782017688/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Vaults"
artist = "Tor"
album = "Blue Book"
track_number = 7
duration_secs = 241

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18507/1782017692/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Cymbol"
artist = "Tor"
album = "Blue Book"
track_number = 8
duration_secs = 318

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18508/1782017696/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Sunyata"
artist = "Tor"
album = "Blue Book"
track_number = 9
duration_secs = 314

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18509/1782017700/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Aura Lore"
artist = "Tor"
album = "Blue Book"
track_number = 10
duration_secs = 254

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18454/1782013713/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Glass & Stone"
artist = "Tor"
album = "Drum Therapy"
track_number = 1
duration_secs = 282

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18455/1782013742/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Heikki"
artist = "Tor"
album = "Drum Therapy"
track_number = 2
duration_secs = 319

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18456/1782013839/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Nomad"
artist = "Tor"
album = "Drum Therapy"
track_number = 3
duration_secs = 311

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18457/1782013875/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "The Thickness"
artist = "Tor"
album = "Drum Therapy"
track_number = 4
duration_secs = 202

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18458/1782013431/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Aperture"
artist = "Tor"
album = "Drum Therapy"
track_number = 5
duration_secs = 242

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18459/1782013776/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Lux"
artist = "Tor"
album = "Drum Therapy"
track_number = 6
duration_secs = 97

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18460/1782013680/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Drum Therapy"
artist = "Tor"
album = "Drum Therapy"
track_number = 7
duration_secs = 257

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18461/1782013910/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Moon II"
artist = "Tor"
album = "Drum Therapy"
track_number = 8
duration_secs = 404

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18462/1782014232/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Paper Rain"
artist = "Tor"
album = "Drum Therapy"
track_number = 9
duration_secs = 282

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18463/1782014259/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Let Me Down"
artist = "Tor"
album = "Drum Therapy"
track_number = 10
duration_secs = 269

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18573/1782021005/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Hammered"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 1
duration_secs = 237

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18574/1782021009/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Little Buddy Move"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 2
duration_secs = 268

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18575/1782021014/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Skylarks"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 3
duration_secs = 485

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18576/1782021019/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Nightfall"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 4
duration_secs = 143

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18577/1782021023/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Scatter"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 5
duration_secs = 308

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18578/1782021028/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Ripple"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 6
duration_secs = 149

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18579/1782021033/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Broken"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 7
duration_secs = 407

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18580/1782021038/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Cage Then Brick"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 8
duration_secs = 117

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18581/1782021043/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "Reverse Learning"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 9
duration_secs = 257

[[track]]
path = "https://fd0b-656e-63ae-4dc7-9209-d0ff-fe17-64d0.7ae01b112262465d9ea5f32af6be2ddd.plex.direct:32400/library/parts/18582/1782021048/file.mp3?X-Plex-Token=Gu_vtYU-4pCLnU5mdU38"
title = "To Dream Is To Forget"
artist = "Hidden Orchestra"
album = "To Dream is to Forget"
track_number = 10
duration_secs = 387
