[[track]]
path = "https://www.youtube.com/watch?v=se647BHCyQ0"
title = "◄ Neurofunk Mix ► Dirty & Dark DnB ☠"
artist = "Db One - DnB Channel"
duration_secs = 3636

[[track]]
path = "https://www.youtube.com/watch?v=hqVJpfFkJ9k"
title = "Hard Neurofunk Drum & Bass Mix (N422)"
artist = "ヤマラ（Music）"
duration_secs = 5004

[[track]]
path = "https://www.youtube.com/watch?v=t7QSzvK4iek"
title = "Moving Shadow Presents: 05.2 Mixed By Calyx"

[[track]]
path = "https://www.youtube.com/watch?v=y6Ya0zIGYxI"
title = "Corrupt Souls - Live in Sevilla - 20/05/2005 #dnb #electronic #neurofunk"
artist = "Katzilla DNB"
duration_secs = 6121
